# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from jetbot/Bot.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import jetbot.msg

class Bot(genpy.Message):
  _md5sum = "676ff8c0e5861dafed1482bc0ebcac80"
  _type = "jetbot/Bot"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 frame_id
CBus cbus
================================================================================
MSG: jetbot/CBus
uint32 frame_id
uint32 fs
ChassisState cp
ChassisState cv
PantiltState gp
PantiltState gv
================================================================================
MSG: jetbot/ChassisState
int32 x
int32 y
int32 z
================================================================================
MSG: jetbot/PantiltState
int16 p
int16 t"""
  __slots__ = ['frame_id','cbus']
  _slot_types = ['uint32','jetbot/CBus']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       frame_id,cbus

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Bot, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.frame_id is None:
        self.frame_id = 0
      if self.cbus is None:
        self.cbus = jetbot.msg.CBus()
    else:
      self.frame_id = 0
      self.cbus = jetbot.msg.CBus()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I6i4h().pack(_x.frame_id, _x.cbus.frame_id, _x.cbus.fs, _x.cbus.cp.x, _x.cbus.cp.y, _x.cbus.cp.z, _x.cbus.cv.x, _x.cbus.cv.y, _x.cbus.cv.z, _x.cbus.gp.p, _x.cbus.gp.t, _x.cbus.gv.p, _x.cbus.gv.t))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.cbus is None:
        self.cbus = jetbot.msg.CBus()
      end = 0
      _x = self
      start = end
      end += 44
      (_x.frame_id, _x.cbus.frame_id, _x.cbus.fs, _x.cbus.cp.x, _x.cbus.cp.y, _x.cbus.cp.z, _x.cbus.cv.x, _x.cbus.cv.y, _x.cbus.cv.z, _x.cbus.gp.p, _x.cbus.gp.t, _x.cbus.gv.p, _x.cbus.gv.t,) = _get_struct_3I6i4h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I6i4h().pack(_x.frame_id, _x.cbus.frame_id, _x.cbus.fs, _x.cbus.cp.x, _x.cbus.cp.y, _x.cbus.cp.z, _x.cbus.cv.x, _x.cbus.cv.y, _x.cbus.cv.z, _x.cbus.gp.p, _x.cbus.gp.t, _x.cbus.gv.p, _x.cbus.gv.t))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.cbus is None:
        self.cbus = jetbot.msg.CBus()
      end = 0
      _x = self
      start = end
      end += 44
      (_x.frame_id, _x.cbus.frame_id, _x.cbus.fs, _x.cbus.cp.x, _x.cbus.cp.y, _x.cbus.cp.z, _x.cbus.cv.x, _x.cbus.cv.y, _x.cbus.cv.z, _x.cbus.gp.p, _x.cbus.gp.t, _x.cbus.gv.p, _x.cbus.gv.t,) = _get_struct_3I6i4h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I6i4h = None
def _get_struct_3I6i4h():
    global _struct_3I6i4h
    if _struct_3I6i4h is None:
        _struct_3I6i4h = struct.Struct("<3I6i4h")
    return _struct_3I6i4h
