// Generated by gencpp from file jetbot/Bot.msg
// DO NOT EDIT!


#ifndef JETBOT_MESSAGE_BOT_H
#define JETBOT_MESSAGE_BOT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <jetbot/CBus.h>

namespace jetbot
{
template <class ContainerAllocator>
struct Bot_
{
  typedef Bot_<ContainerAllocator> Type;

  Bot_()
    : frame_id(0)
    , cbus()  {
    }
  Bot_(const ContainerAllocator& _alloc)
    : frame_id(0)
    , cbus(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _frame_id_type;
  _frame_id_type frame_id;

   typedef  ::jetbot::CBus_<ContainerAllocator>  _cbus_type;
  _cbus_type cbus;




  typedef boost::shared_ptr< ::jetbot::Bot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetbot::Bot_<ContainerAllocator> const> ConstPtr;

}; // struct Bot_

typedef ::jetbot::Bot_<std::allocator<void> > Bot;

typedef boost::shared_ptr< ::jetbot::Bot > BotPtr;
typedef boost::shared_ptr< ::jetbot::Bot const> BotConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetbot::Bot_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetbot::Bot_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jetbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'jetbot': ['/home/bj/workspace/ros/car_ros/src/jetbot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jetbot::Bot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetbot::Bot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbot::Bot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbot::Bot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbot::Bot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbot::Bot_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetbot::Bot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "676ff8c0e5861dafed1482bc0ebcac80";
  }

  static const char* value(const ::jetbot::Bot_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x676ff8c0e5861dafULL;
  static const uint64_t static_value2 = 0xed1482bc0ebcac80ULL;
};

template<class ContainerAllocator>
struct DataType< ::jetbot::Bot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetbot/Bot";
  }

  static const char* value(const ::jetbot::Bot_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetbot::Bot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 frame_id\n\
CBus cbus\n\
================================================================================\n\
MSG: jetbot/CBus\n\
uint32 frame_id\n\
uint32 fs\n\
ChassisState cp\n\
ChassisState cv\n\
PantiltState gp\n\
PantiltState gv\n\
================================================================================\n\
MSG: jetbot/ChassisState\n\
int32 x\n\
int32 y\n\
int32 z\n\
================================================================================\n\
MSG: jetbot/PantiltState\n\
int16 p\n\
int16 t\n\
";
  }

  static const char* value(const ::jetbot::Bot_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetbot::Bot_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame_id);
      stream.next(m.cbus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Bot_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetbot::Bot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetbot::Bot_<ContainerAllocator>& v)
  {
    s << indent << "frame_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.frame_id);
    s << indent << "cbus: ";
    s << std::endl;
    Printer< ::jetbot::CBus_<ContainerAllocator> >::stream(s, indent + "  ", v.cbus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETBOT_MESSAGE_BOT_H
