// Generated by gencpp from file jetbot/Uwb.msg
// DO NOT EDIT!


#ifndef JETBOT_MESSAGE_UWB_H
#define JETBOT_MESSAGE_UWB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jetbot
{
template <class ContainerAllocator>
struct Uwb_
{
  typedef Uwb_<ContainerAllocator> Type;

  Uwb_()
    : frame_id(0)
    , flag(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , w(0.0)  {
    }
  Uwb_(const ContainerAllocator& _alloc)
    : frame_id(0)
    , flag(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _frame_id_type;
  _frame_id_type frame_id;

   typedef uint8_t _flag_type;
  _flag_type flag;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _w_type;
  _w_type w;




  typedef boost::shared_ptr< ::jetbot::Uwb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetbot::Uwb_<ContainerAllocator> const> ConstPtr;

}; // struct Uwb_

typedef ::jetbot::Uwb_<std::allocator<void> > Uwb;

typedef boost::shared_ptr< ::jetbot::Uwb > UwbPtr;
typedef boost::shared_ptr< ::jetbot::Uwb const> UwbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetbot::Uwb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetbot::Uwb_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jetbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'jetbot': ['/home/bj/workspace/ros/car_ros/src/jetbot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jetbot::Uwb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetbot::Uwb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbot::Uwb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbot::Uwb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbot::Uwb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbot::Uwb_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetbot::Uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "07f717daa1ab5369ea12dffa912f8623";
  }

  static const char* value(const ::jetbot::Uwb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x07f717daa1ab5369ULL;
  static const uint64_t static_value2 = 0xea12dffa912f8623ULL;
};

template<class ContainerAllocator>
struct DataType< ::jetbot::Uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetbot/Uwb";
  }

  static const char* value(const ::jetbot::Uwb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetbot::Uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 frame_id\n\
uint8 flag\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 w\n\
";
  }

  static const char* value(const ::jetbot::Uwb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetbot::Uwb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame_id);
      stream.next(m.flag);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Uwb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetbot::Uwb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetbot::Uwb_<ContainerAllocator>& v)
  {
    s << indent << "frame_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.frame_id);
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETBOT_MESSAGE_UWB_H
